### PR TITLE
[yarpWholeBodyState] Refactor of base state estimation

### PR DESCRIPTION
**Pull request by traversaro**
Not the base estimation algorithm is enclosed in a class for better modularity.

### CODE REVIEW

**Comment by traversaro** [comment]
cc @naveenoid @francesco-romano

**Comment by francesco-romano** [comment]
@traversaro good to me.
Can I add my changes here before merging?

**Comment by traversaro** [comment]
Yes!

**Comment by traversaro** [comment]
cc @naveenoid did you check? It seems ok to you?

**Comment by naveenoid** [comment]
Test response perfect. Go ahead and merge when happy.

**Pull request merged**
