### PR TITLE
Add support for reading floating base state (position, velocity and acceleration) from a remote yarp port

### PR DESCRIPTION
**Pull request by traversaro**
Adding support for reading the floating base state from a remote port. For now we are using a generic bottle using the format used by wholeBodyDynamicsTree , but the idea is that in the future we can define a proper type for the  floating base state (using yarp IDLs stuff, so thrift or rosmsg) and have multiple module that stream the floating base state estimation (for example the big filter that we are going to develop. 

Other modification:
 *  moved the floating base state estimators to a separate file
  * deprecated some options such as `WORLD_REFERENCE_FRAME` and `estimateBasePosVel`, substituted by `estimateBaseState` and `localWorldReferenceFrame`. They are still supported for the moment, but a warning will be printed and eventually they will be removed.

cc @naveenoid can you review the changes in the local estimation part? Thanks!

### CODE REVIEW

**Comment by traversaro** [comment]
@naveenoid Did you have the chance to check this PR?

**Comment by naveenoid** [comment]
Sorry mate will do tomorrow. I somehoe did not receive this notifications
>:(

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

On Fri, Apr 10, 2015 at 6:35 PM, Silvio Traversaro <notifications@github.com

**Comment by francesco-romano** [comment]
Time is running out [cit.]

Merging

**Comment by traversaro** [comment]
cc @naveenoid I hope it does not break any existing behaviour, merging.

**Comment by naveenoid** [comment]
Verified. Sorry for poor response. Hope it didnt derail your demo plans too
much. I like the current design.

---
Naveen Kuppuswamy, PhD
Post-doctoral Fellow,
Cognitive Humanoids Lab,
Department of Robotics, Brain and Cognitive Sciences (RBCS),
Istituto Italiano di Tecnologia, Genova, Italy

On Tue, Apr 14, 2015 at 6:41 PM, Silvio Traversaro <notifications@github.com

**Pull request merged**
